# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.0.1
maven_group=com.daereplication

# Dependencies
fabric_api_version=0.156.0+26.2
tr_energy_version=5.0.0
tech_reborn_version=6.1.0

jei_version=30.24.0.170
rei_version=26.2.820
cloth_config=26.2.155
architectury_version=21.0.7